In [6]:
import numpy as np

x = np.array([1,2,3,4])

print(x)
print(x.shape)
x=x.reshape(-1,1)
print(x)
print(x.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

X=np.array([12,41,42,42,15,22]).reshape(-1,1)
y=np.array([48,524,55,21,25,24])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

print(X_train)
print(y_train)
print(X_test)
print(y_test)



[[22]
 [42]
 [15]
 [42]]
[24 55 25 21]
[[12]
 [41]]
[ 48 524]
